import { Ecosystem, Technology, Project, Metric } from '@/types/index';

export const ecosystems: Ecosystem[] = [
  {
    id: 'education',
    name: 'Educación',
    description: 'Transformando el aprendizaje mediante inteligencia artificial adaptativa y sistemas de análisis predictivo que personalizan cada experiencia educativa.',
    color: 'from-blue-500 to-cyan-500',
    technologies: ['AI', 'Machine Learning', 'Analítica Avanzada'],
    projects: ['AdaptiveAI', 'PredictiveLearn'],
    icon: '🎓',
  },
  {
    id: 'architecture',
    name: 'Arquitectura',
    description: 'Revolucionando el diseño y construcción con simulaciones 3D avanzadas, análisis estructural inteligente y automatización de procesos complejos.',
    color: 'from-purple-500 to-pink-500',
    technologies: ['3D Rendering', 'Simulación', 'Cloud Computing'],
    projects: ['DesignAI', 'StructureOptimize'],
    icon: '🏗️',
  },
  {
    id: 'software',
    name: 'Desarrollo',
    description: 'Creando sistemas distribuidos inteligentes, APIs escalables y arquitecturas de microservicios para la próxima generación de aplicaciones.',
    color: 'from-green-500 to-emerald-500',
    technologies: ['APIs Inteligentes', 'Sistemas Distribuidos', 'Automatización'],
    projects: ['CloudCore', 'DevOpsAI'],
    icon: '💻',
  },
  {
    id: 'mobility',
    name: 'Movilidad',
    description: 'Impulsando la movilidad autónoma, optimización de tráfico en tiempo real y logística inteligente con procesamiento de datos masivos.',
    color: 'from-orange-500 to-red-500',
    technologies: ['IoT', 'Real-time Analytics', 'ML'],
    projects: ['AutonomicFlow', 'TrafficML'],
    icon: '🚗',
  },
  {
    id: 'finance',
    name: 'Finanzas',
    description: 'Desarrollando sistemas de detección avanzada de fraudes, predicción de mercados y gestión inteligente de riesgos financieros.',
    color: 'from-yellow-500 to-amber-500',
    technologies: ['Ingeniería de Datos', 'ML', 'Quantum'],
    projects: ['FraudShield', 'MarketPredictor'],
    icon: '💰',
  },
];

export const technologies: Technology[] = [
  {
    id: 'ai',
    name: 'Inteligencia Artificial',
    description: 'Sistemas de IA generativa y especializada para resolver problemas complejos en tiempo real.',
    icon: '🤖',
    color: 'from-blue-500 to-cyan-500',
    category: 'Core',
  },
  {
    id: 'data-engineering',
    name: 'Ingeniería de Datos',
    description: 'Pipelines de datos escalables, procesamiento en streaming y almacenamiento inteligente.',
    icon: '📊',
    color: 'from-purple-500 to-pink-500',
    category: 'Core',
  },
  {
    id: 'machine-learning',
    name: 'Machine Learning',
    description: 'Modelos predictivos, clasificación y análisis de patrones en datos masivos.',
    icon: '🧠',
    color: 'from-green-500 to-emerald-500',
    category: 'Core',
  },
  {
    id: 'cloud-computing',
    name: 'Cloud Computing',
    description: 'Infraestructura distribuida, serverless, y orquestación de contenedores.',
    icon: '☁️',
    color: 'from-orange-500 to-red-500',
    category: 'Infrastructure',
  },
  {
    id: 'automation',
    name: 'Automatización',
    description: 'RPA, flujos de trabajo inteligentes y procesos autónomos de extremo a extremo.',
    icon: '⚙️',
    color: 'from-yellow-500 to-amber-500',
    category: 'Infrastructure',
  },
  {
    id: 'distributed-systems',
    name: 'Sistemas Distribuidos',
    description: 'Arquitecturas descentralizadas, consenso distribuido y computación paralela.',
    icon: '🔗',
    color: 'from-pink-500 to-rose-500',
    category: 'Architecture',
  },
  {
    id: 'analytics',
    name: 'Analítica Avanzada',
    description: 'Business intelligence, visualización de datos y análisis prescriptivo.',
    icon: '📈',
    color: 'from-indigo-500 to-purple-500',
    category: 'Analytics',
  },
  {
    id: 'apis',
    name: 'APIs Inteligentes',
    description: 'Interfaces de usuario inteligentes, gateways adaptativos y orquestación de servicios.',
    icon: '🔌',
    color: 'from-cyan-500 to-blue-500',
    category: 'Core',
  },
];

export const projects: Project[] = [
  {
    id: 'adaptive-ai',
    name: 'AdaptiveAI Learning',
    description: 'Plataforma educativa que adapta contenido en tiempo real basado en el aprendizaje del estudiante.',
    industry: 'Educación',
    technologies: ['AI', 'Machine Learning', 'Analítica Avanzada'],
    status: 'Active',
    impact: 'Mejora de 40% en retención de estudiantes',
    image: '🎯',
  },
  {
    id: 'design-ai',
    name: 'DesignAI Suite',
    description: 'Generación automática de diseños arquitectónicos con optimización estructural.',
    industry: 'Arquitectura',
    technologies: ['3D Rendering', 'AI', 'Simulación'],
    status: 'Active',
    impact: 'Reducción de 60% en tiempo de diseño',
    image: '🏗️',
  },
  {
    id: 'cloud-core',
    name: 'CloudCore',
    description: 'Plataforma serverless de próxima generación con auto-escalado inteligente.',
    industry: 'Software',
    technologies: ['Cloud Computing', 'APIs Inteligentes', 'Sistemas Distribuidos'],
    status: 'Active',
    impact: 'Reducción de costos del 70%',
    image: '☁️',
  },
  {
    id: 'autonomic-flow',
    name: 'AutonomicFlow',
    description: 'Sistema de movilidad autónoma con optimización de rutas en tiempo real.',
    industry: 'Movilidad',
    technologies: ['IoT', 'Real-time Analytics', 'ML'],
    status: 'Research',
    impact: 'Reducción de congestión vehicular del 45%',
    image: '🚗',
  },
  {
    id: 'fraud-shield',
    name: 'FraudShield',
    description: 'Detección de fraudes con redes neuronales de última generación.',
    industry: 'Finanzas',
    technologies: ['ML', 'Ingeniería de Datos', 'Real-time Analytics'],
    status: 'Active',
    impact: 'Prevención del 99.2% de fraudes',
    image: '🛡️',
  },
  {
    id: 'market-predictor',
    name: 'MarketPredictor',
    description: 'Análisis predictivo de mercados financieros con modelos cuánticos.',
    industry: 'Finanzas',
    technologies: ['ML', 'Quantum', 'Analítica Avanzada'],
    status: 'Research',
    impact: 'Predicción con 85% de precisión',
    image: '📊',
  },
];

export const metrics: Metric[] = [
  {
    label: 'Ecosistemas Activos',
    value: 5,
    unit: '',
    prefix: '',
  },
  {
    label: 'Productos Desarrollados',
    value: 12,
    unit: '+',
    prefix: '',
  },
  {
    label: 'Líneas de Investigación',
    value: 25,
    unit: '+',
    prefix: '',
  },
  {
    label: 'Usuarios Alcanzados',
    value: 500000,
    unit: '+',
    prefix: '',
  },
  {
    label: 'Datos Procesados',
    value: 1.2,
    unit: 'PB',
    prefix: '',
  },
];
